SELECT A.NAME AS "DEPARTMENT"
    ,  B.NAME AS "EMPLOYEE"
    ,  B.SALARY
  FROM DEPARTMENT A
    ,  EMPLOYEE B
 WHERE A.ID = B.DEPARTMENTID
   AND 3 > (
        SELECT COUNT(DISTINCT(C.SALARY))
          FROM EMPLOYEE C
         WHERE B.DEPARTMENTID = C.DEPARTMENTID
           AND B.SALARY < C.SALARY
   )